version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: django_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: funcionarios
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
